-- DRY-RUN ONLY: generated candidate updates. Do not apply to production without explicit approval.
-- Intended fields: CatalogSet.logoImageUrl/symbolImageUrl plus sourcePayload provenance.
-- This file was NOT executed by the campaign.
BEGIN;
UPDATE "CatalogSet" SET "logoImageUrl" = 'https://assets.tcgdex.net/en/swsh/swsh10.5/logo.png', "symbolImageUrl" = 'https://assets.tcgdex.net/univ/swsh/swsh10.5/symbol.png', "sourcePayload" = COALESCE("sourcePayload", '{}'::jsonb) || jsonb_build_object('__oripaSetImageTruthCandidate', '{"provider":"tcgdex:en","providerSetId":"swsh10.5","providerName":"Pokémon GO","matchRule":"exact_normalized_name","confidence":"high","score":1,"generatedAt":"2026-06-05T12:28:50.107Z","validation":{"logoImageUrl":{"url":"https://assets.tcgdex.net/en/swsh/swsh10.5/logo.png","ok":true,"status":200,"contentType":"image/png","bytes":44523,"signature":"89504e470d0a1a0a0000000d49484452"},"symbolImageUrl":{"url":"https://assets.tcgdex.net/univ/swsh/swsh10.5/symbol.png","ok":true,"status":200,"contentType":"image/png","bytes":1535,"signature":"89504e470d0a1a0a0000000d49484452"}}}'::jsonb) WHERE "id" = 'cmprbv11m0g3ztm8g48ga8zya';
UPDATE "CatalogSet" SET "logoImageUrl" = NULL, "symbolImageUrl" = 'https://assets.tcgdex.net/univ/sm/sma/symbol.png', "sourcePayload" = COALESCE("sourcePayload", '{}'::jsonb) || jsonb_build_object('__oripaSetImageTruthCandidate', '{"provider":"tcgdex:en","providerSetId":"sma","providerName":"Hidden Fates Shiny Vault","matchRule":"exact_normalized_name","confidence":"high","score":1,"generatedAt":"2026-06-05T12:28:50.107Z","validation":{"logoImageUrl":null,"symbolImageUrl":{"url":"https://assets.tcgdex.net/univ/sm/sma/symbol.png","ok":true,"status":200,"contentType":"image/png","bytes":1944,"signature":"89504e470d0a1a0a0000000d49484452"}}}'::jsonb) WHERE "id" = 'cmprc628c03k3tmasoz07eqyh';
UPDATE "CatalogSet" SET "logoImageUrl" = 'https://assets.tcgdex.net/en/pl/ru1/logo.png', "symbolImageUrl" = 'https://assets.tcgdex.net/univ/pl/ru1/symbol.png', "sourcePayload" = COALESCE("sourcePayload", '{}'::jsonb) || jsonb_build_object('__oripaSetImageTruthCandidate', '{"provider":"tcgdex:en","providerSetId":"ru1","providerName":"Pokémon Rumble","matchRule":"exact_normalized_name","confidence":"high","score":1,"generatedAt":"2026-06-05T12:28:50.107Z","validation":{"logoImageUrl":{"url":"https://assets.tcgdex.net/en/pl/ru1/logo.png","ok":true,"status":200,"contentType":"image/png","bytes":440752,"signature":"89504e470d0a1a0a0000000d49484452"},"symbolImageUrl":{"url":"https://assets.tcgdex.net/univ/pl/ru1/symbol.png","ok":true,"status":200,"contentType":"image/png","bytes":38954,"signature":"89504e470d0a1a0a0000000d49484452"}}}'::jsonb) WHERE "id" = 'cmprcxrel03f1tmxwmom8323l';
ROLLBACK;
-- Replace ROLLBACK with COMMIT only after local/staging approval + post-apply audit.
